### ISSUE TITLE
How to build framework from source codes?

### ISSUE THREAD

**Issue by KanybekMomukeyev** [peter-iakovlev/TelegramCore#1]
Hi, thanks for sharing source codes!
How to build framework from source codes? In my case there are some missing frameworks:
MTProto, SwiftSignalKit, .....

**Comment by nikit6000** [comment]
For successful build you must use this frameworks:
PostBox: https://github.com/peter-iakovlev/Postbox
MTProtoKit: https://github.com/peter-iakovlev/Postbox
SSignalKit: https://github.com/peter-iakovlev/Signals

**Comment by KanybekMomukeyev** [comment]
@nikit6000 thanks for reply!
Already did that, there is some simple way to build: 
https://github.com/overtake/TelegramSwift

**Comment by KanybekMomukeyev** [comment]
@nikit6000  but have another issue, not able to build TelegramMac app from source codes:
https://github.com/overtake/TelegramSwift

**Comment by peter-iakovlev** [comment]
@KanybekMomukeyev it would be better to discuss the issue in [https://github.com/overtake/TelegramSwift](url)

**Comment by KanybekMomukeyev** [comment]
@peter-iakovlev thanks for reply!
Also thanks for last commit to https://github.com/overtake/TelegramSwift, that fixed all issues related to success build! 
Also i would like to mention about new Telegram X, the speed is amazing, very fast app, maybe fastest app!  I'm very excited about open source Telegram X!
