### ISSUE TITLE
Telegram X source code

### ISSUE THREAD

**Issue by laizaraujo** [peter-iakovlev/TelegramCore#11]
Would it be possible for you to release the complete Telegram code in swift? 
I'm developing a Telegram client application and would like to start developing it with the source code in Swift.

Thank you.

**Comment by nikit6000** [comment]
Telegram client is already implemented in this framework. First step look at "ApplicationContext.swift" and "AppDelegate.swift" in [TelegramSwift](https://github.com/overtake/TelegramSwift).

**Comment by peter-iakovlev** [comment]
The source code for Telegram X will be released eventually, no later than the first official public release of the app.

**Comment by bernaferrari** [comment]
Hey, @peter-iakovlev.
No pressure (and I **really** hate to ask this), but now that it is official, is there any ETA/plans for publishing the code from Telegram X for Android? I didn't find anything, and their github page won't even accept "issues" 😢

**Comment by Yvrabu** [comment]
Hello @peter-iakovlev I was also wondering if the Telegram X for Android source code will ever be published?

**Comment by lampanon** [comment]
@bernaferrari @Yvrabu why do you ask here about the android app? This is the iOS-related github page.

Btw, here is an issue tracker for Telegram X on Android - https://bitbucket.org/challegram/challegram/issues

I think that Peter had in mind a stable release. At the moment, both X are in beta and they are quite unstable.

**Comment by bernaferrari** [comment]
@lampanon because, as I mentioned above, Telegram for Android does not have a public issue tracker. So, knowing Peter works at Telegram, and most people here are developers, I thought he would know anything about it. 
Thanks for the bitbucket repo, I would have never guessed Telegram X is called "challegram" and they are using another website from (yet) another developer for it.
As of the stable release, there is no mention on Play Store or their blog post that it is still on beta, so thanks for clarifying.

**Comment by lampanon** [comment]
@bernaferrari 
> there is no mention on Play Store or their blog post that it is still on beta
Yeah, but there is a mention in the blog that:
> Both these apps are experimental
They don't call it exactly a beta, but coupled with the fact that in these apps a huge number of features don't work and still a huge number of issues, these apps can't be called "stable versions" in any way. Rather an open beta test.

That's what Peter said about the app publication in the AppStore:
> It's an official public preview of what we've been working on

> I would have never guessed Telegram X is called "challegram" and they are using another website from (yet) another developer for it.
Originally this application was developed as part of the Telegram Android Challenge and was called Challegram. I guess that after the app-winner of the contest became an official application, it was convenient for the developer to continue using the already existing bug tracker. 

Anyway, here is a group, dedicated to testing and bug reporting Telegram X for Android - https://t.me/tgandroidtests

**Comment by nirizr** [comment]
> Btw, here is an issue tracker for Telegram X on Android - 
> https://bitbucket.org/challegram/challegram/issues

This is no longer accessible. Is there any intention of publishing the telegramX source code?
