### ISSUE TITLE
Notifications not cleared when messages are read on other client

### ISSUE THREAD

**Issue by rodriguezst** [peter-iakovlev/TelegramCore#12]
On the original Telegram app, if a message is read on another client the notification for that message is cleared automatically. This doesn't happen with Telegram X. The notification only gets cleared if the app is opened.

**Comment by farovitus** [comment]
I am having the same issue, using Pixel 2 XL (8.1, stock rom) @peter-iakovlev

**Comment by 8la** [comment]
Same here. They are cleared if you tap on individual notification but when grouped this does not work
