### ISSUE TITLE
xcode No such module 'Postbox'

### ISSUE THREAD

**Issue by jalalimehdi** [peter-iakovlev/TelegramCore#16]

**Comment by GENEMATOR** [comment]
+1

**Comment by shekoofev** [comment]
what happened? Could you solve this problem?

**Comment by Vahn84** [comment]
same here

**Comment by shivanraptor** [comment]
You can find "Postbox" here: https://github.com/peter-iakovlev/Postbox

You will need other repos from Peter Iakovlev as well. Clone the repo and add to Target Dependencies.
