### ISSUE TITLE
Telegram X does not appear in the system share sheet 

### ISSUE THREAD

**Issue by sposterkil** [peter-iakovlev/TelegramCore#4]
Presumably just needs a sharing extension to be created or ported over from the old app. 

Btw, if this is not the right place to report bugs, let me know - I’ll be opening a few here today.

**Comment by sposterkil** [comment]
iPhone 7+, iOS 11.2.1, Telegram X 5.0 from App Store.

**Comment by andrebraga** [comment]
It totally does. You have to enable it.

**Comment by sposterkil** [comment]
Oh, I’m incompetent.
